### PR TITLE
make a "pure" orig.tar.xz for Debian

### PR DESCRIPTION
**Pull request by tmancill**
Hi @xylo04 - this isn't really a pull-request as much as an easy way to demonstrate how I ended up generating kel-agent_0.2.2.orig.tar.xz for the Debian packaging.

### CODE REVIEW

**Comment by xylo04** [comment]
Good to know, thank you @tmancill. Might as well merge it!

**Comment by xylo04** [comment]
Oh, but removing `debian` will prevent me from building my own .deb files for release here... Well, I can remove that part and keep the rest of the tar command.

**Comment by tmancill** [comment]
> Oh, but removing `debian` will prevent me from building my own .deb files for release here... Well, I can remove that part and keep the rest of the tar command.

Right.  I am thinking maybe we add add a separate target.  Maybe `deb-orig-tarball` - does that sound okay?

**Comment by xylo04** [comment]
Yes! Sounds good

**Pull request merged**
